### ISSUE TITLE
Ignore lockfiles by default

### ISSUE THREAD

**Issue by dantman** [leandrosimoes/project-urls-manager-vscode-extension#23]
npm and yarn generate lockfiles with urls in them but aren't excluded in the default list of paths. So the lockfile can contribute thousands of URLs to package tarballs to the urls manager.

- package-lock.json
- yarn.lock

**Comment by leandrosimoes** [comment]
Hi @dantman ! Thanks for the report. I'll implement that and release a new version asap.

**Comment by leandrosimoes** [comment]
Done!

https://github.com/leandrosimoes/project-urls-manager-vscode-extension/releases/tag/v1.2.2

Updates are released on demand if you can't find it in the market place, just wait a few hours and try again.
