### ISSUE TITLE
✨ [FEATURE] Ref source of every url

### ISSUE THREAD

**Issue by TieWay59** [leandrosimoes/project-urls-manager-vscode-extension#44]
### Describe what the feature is about?

Hi @leandrosimoes, I found this project from the market, because I have a markdown project with 100+ URLs in it. I was hoping to find some tools to view and manage it.

I see your awesome project as a nice start, I hope it can offer the ability to check where some is used.

I'm new here, but don't know where to start to look. 

BTW, I don't wish to interrupt your roadmap, and I'd understand if you don't feel this is worth adding.

### Anything else?

![image](https://github.com/leandrosimoes/project-urls-manager-vscode-extension/assets/40034603/a117474a-e1af-4c68-8625-c88ed9b084e4)

Maybe we need an icon on the right of the URL to jump to the origin context.

**Comment by leandrosimoes** [comment]
Hi @TieWay59,

Thanks for your suggestion.
I think this is a really good idea, I'll definitely add this to the roadmap.

Thanks.

**Comment by leandrosimoes** [comment]
Hi @TieWay59,

Feature implemented in version https://github.com/leandrosimoes/project-urls-manager-vscode-extension/releases/tag/v1.2.5

Please, consider giving the [extension a star](https://marketplace.visualstudio.com/items?itemName=Leandro.project-urls-manager&ssr=false#review-details)!

Thanks.

**Comment by TieWay59** [comment]
@leandrosimoes Thank you! This is the very feature in need.

![image](https://github.com/leandrosimoes/project-urls-manager-vscode-extension/assets/40034603/18d88e36-a1f4-4cad-b487-f5b18cc65c2a)
